### ISSUE TITLE
Is this Eliza example invalid since it uses a custom intent?

### ISSUE THREAD

**Issue by mrchess** [actions-on-google/actionssdk-eliza-nodejs#6]
In `action.json`, there is an intent called:

```
      "intent": {
        "name": "raw.input",
        "parameters": [{
          "name": "feelings",
          "type": "SchemaOrg_Text"
        }],
```

However I can never get this intent to trigger when using the test environment in the actions console. Every time I send a message, it just triggers `actions.intent.TEXT`.

Further research took me to this StackOverflow question: https://stackoverflow.com/questions/41427697/expectedinputs-possible-intents-only-works-with-assistant-intent-action-text

In which the Google Engineer, Leon Nicholls, says:

> When using the Actions SDK, only the TEXT intent is supported. You have to use your own NLU to parse the raw text input provided by the user.

> If you don't have your own NLU, then we recommend using API.AI.

> There are no plans to provide NLU with the Actions SDK

Can someone explain to me why this **custom intent** exists in the `action.json`, along with the supporting code in `index.js.` then if it is impossible to trigger? Isn't it misleading?

**Comment by mrchess** [comment]
On a similar note, on the documentation: https://developers.google.com/actions/sdk/define-actions

Why does it have a custom intent here as well? `"name": "com.example.sekai.BUY"`.

If you cannot trigger it with the Action SDK?

**Comment by mrchess** [comment]
I think the root of the problem is it seems like you can use `action.json`, the `action-sdk`, and `custom intents` as an alternative to DialogFlow UI. This is because the syntax, phrases, and overall JSON structure is designed very closely to the DialogFlow interface.

However be warned that these are two very different things.

Maybe I didn't read the original documentation enough, but it wasn't very clear that these are two distinct concepts.

**Comment by taycaldwell** [comment]
The TEXT intent will be triggered if the phrase matches one of the query patterns found in `triggerPhrases` for the intents defined in the action package.
